site_name: olympic_history
site_description: Desafio Celero!!
repo_url: https://github.com/Dan-source/olympic_history
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Dan-source">Dan-source</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
