# Generated by Django 4.0.3 on 2022-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_alter_athlete_id_alter_athleteevent_id_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sport',
            field=models.CharField(max_length=200, verbose_name='Sport'),
        ),
    ]
